AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['\A\s*#'] # ignore comments