require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/firebase_dump.rb'
    - 'db/firebase_dump.template.rb'
    - 'db/migrate_data_from_firebase.rb'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['\A\s*#'] # ignore comments

Rails/HasAndBelongsToMany:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Enabled: true
  ExcludedMethods: ['describe', 'context', 'define', 'factory']
  Exclude:
    - 'spec/rails_helper.rb'