default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: apigator9999_development
  username: apigator9999
  password: apigator9999
  host: localhost
  port: 5432

test:
  <<: *default
  database: apigator9999_test
  username: apigator9999
  password: apigator9999
  host: localhost
  port: 5432

production:
  <<: *default
  database: apigator9999_production
  username: <%= ENV['APIGATOR9999_DB_USER'] %>
  password: <%= ENV['APIGATOR9999_DB_PASSWORD'] %>